### ISSUE TITLE
Discuss 2.0 version of the protocol

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-protocol#1]
I started to implement a 2.0 version of the protocol. High level the changes are:

- alignment of the protocol with the VSCode exension API. As a result the properties of a request param object conform to parameters in the API. So for example if the VSCode extension API takes a text document has the first parameter the corresponding parameter literal in the JSON RPC protocol now has a property `textDocument`. 
- consistent support for language identifiers. This means that the language ID is passed to the server via the open notification. Further references to the text document don't transfer this informaiton anymore.
- support for version numbers on documents. The initial version number is send to the server via the open notification. Document change notification do carry information about VSCode's version number as well.

I moved to version 2.0 since especially the first item makes the changes incompatible with the 1.0 version. However I think they are worthwhile the change and easy to adopt since they are mostly JSON literal changes.

The document [here](https://github.com/Microsoft/vscode-languageserver-protocol/blob/master/versions/protocol-2-0.md) describes the changes. It uses a New / Changed annotation to highlight the changes (see below).

Feedback to the new version is highly welcome.

![capture](https://cloud.githubusercontent.com/assets/1931590/14320205/82c942a6-fc14-11e5-9dc3-4b5235e27101.png)

**Comment by dbaeumer** [comment]
@aeschli @felixfbecker would like to get your feedback on this.

**Comment by daviwil** [comment]
Looks good overall!  I like the introduction of versioning.  Did you run into some problems where versioning was needed, or is this becoming a core concept in the VS Code API that the protocol is now responding to?

**Comment by daviwil** [comment]
Also, when are you rolling out the new protocol?  After 1.0?

**Comment by sridmad** [comment]
+1 on more information about document versioning would be useful.

I would also like to see the following in the protocol.
1. Cancellation of previous requests. We can cancel longer operations if they have been cancelled by user or due to user actions.
2. The protocol has equivalent of onDidChangeTextDocument, onDidCloseOpenDocument, onDidOpenTextDocument but missing onDidSaveTextDocument.

For most operations we have to mimic the contents of opened and changed documents on the language server side and getting onDidSave for the text document will be a good point to clean up the tracking structures.

**Comment by dbaeumer** [comment]
Regarding versioning: the use case is auto / quick fix support. Since the whole communication is async and we allow the use to continue typing when code actions are computed having a version number will allow to 'annotate' a code action with a version number. When selected the code can check the code action's version number against the current document's version number and if they differ re-compute the code action.

**Comment by dbaeumer** [comment]
I will add onDidSaveTextDocument to the 2.0 protocol. Good idea. I will also look what we can do in terms of cancelation. I fully agree that this would be cool especially since the VSCode extension API has fully support for cancelation.

**Comment by dbaeumer** [comment]
Support for save notification got added: https://github.com/Microsoft/vscode-languageserver-node/tree/dbaeumer/14

**Comment by daviwil** [comment]
Versioning totally makes sense for quick fixes.  I recently started implementing quick fix support and wondered about this.

**Comment by dbaeumer** [comment]
I first cut to support cancellation has been added. It is on branch:  https://github.com/Microsoft/vscode-languageserver-node/tree/dbaeumer/14

**Comment by dbaeumer** [comment]
I pushed version 2.0 of the protocol today to the git repository and npm modules

**Comment by daviwil** [comment]
When should we start using this, the first release after 1.0?

**Comment by daviwil** [comment]
1.0 of VS Code, I mean

**Comment by dbaeumer** [comment]
You can already start using it. It doesn't require VSCode 1.0 version.

**Comment by daviwil** [comment]
Actually I was more concerned about whether I will run into issues if I *don't* start using it yet for VS Code 1.0 :)

**Comment by dbaeumer** [comment]
No both combinations are fine.
