### ISSUE TITLE
Request cancellation

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode-languageserver-protocol#2]
Hey! Firstly, I'd like to say great thanks for this protocol, I've been dreaming about this for a long time now and you guys finally designed a good one! I'm currently implementing a [language server for the Haxe language](https://github.com/nadako/haxe-languageserver) using this.

Now I have a question about request cancellation. It's not clear whether how exactly the server should react to these notifications. Should it send any response back or just silently cancel the action and act like there was no request at all?

Please, clarify that in the specification!

**Comment by dbaeumer** [comment]
Again, good catch. The request needs to returns a response even if canceled. This is designed that why so that a request could return a 'partial' result on cancel. Will clarify in the specification.
